/**
 * Pexels image fetcher.
 *
 * Reads search queries from src/data/imageQueries.ts, queries the Pexels
 * /v1/search endpoint, picks the top landscape result per slot, and writes
 * the resulting URL map to src/data/imageUrls.ts.
 *
 * Run with:
 *   PEXELS_API_KEY=xxx npm run fetch-images
 * or set PEXELS_API_KEY in .env.local (preferred) or .env at the repo root.
 *
 * Get a free key at https://www.pexels.com/api/
 */
import { config as dotenvConfig } from 'dotenv'
// Match the env-file convention used by scripts/mcp-image-server.mjs:
// prefer .env.local (gitignored), fall back to .env. Both are silently
// skipped if absent, so an external env still wins.
dotenvConfig({ path: '.env.local' })
dotenvConfig({ path: '.env' })
import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { IMAGE_QUERIES } from '../src/data/imageQueries'

type PexelsPhoto = {
  id: number
  src: {
    original: string
    large2x: string
    large: string
    medium: string
    small: string
    portrait: string
    landscape: string
    tiny: string
  }
  alt?: string
}
type PexelsSearchResponse = {
  photos: PexelsPhoto[]
  total_results: number
}

const API_KEY = process.env.PEXELS_API_KEY
if (!API_KEY) {
  console.error('\n  Missing PEXELS_API_KEY.')
  console.error('  Get a free key at https://www.pexels.com/api/ and add it to .env\n')
  process.exit(1)
}

const ROOT = resolve(fileURLToPath(import.meta.url), '..', '..')
const OUT = resolve(ROOT, 'src/data/imageUrls.ts')

const BASE = 'https://api.pexels.com/v1/search'
const PER_PAGE = 5

const searchCache = new Map<string, string>()

async function pickPhoto(query: string, size: 'large2x' | 'large' = 'large2x'): Promise<string> {
  const cached = searchCache.get(query)
  if (cached) return cached

  const url = `${BASE}?query=${encodeURIComponent(query)}&per_page=${PER_PAGE}&orientation=landscape`
  const res = await fetch(url, { headers: { Authorization: API_KEY! } })
  if (!res.ok) {
    throw new Error(`Pexels search failed for "${query}": ${res.status} ${res.statusText}`)
  }
  const data = (await res.json()) as PexelsSearchResponse
  const photo = data.photos[0]
  if (!photo) {
    throw new Error(`No Pexels results for "${query}"`)
  }
  const link = photo.src[size]
  searchCache.set(query, link)
  process.stdout.write(`  ✓ ${query.padEnd(48)} → photo ${photo.id}\n`)
  return link
}

async function pickMany(queries: readonly string[]): Promise<string[]> {
  const results: string[] = []
  for (const q of queries) results.push(await pickPhoto(q))
  return results
}

async function pickRecord<K extends string>(
  queries: Record<K, string>,
): Promise<Record<K, string>> {
  const out = {} as Record<K, string>
  for (const key of Object.keys(queries) as K[]) {
    out[key] = await pickPhoto(queries[key])
  }
  return out
}

/**
 * Preserve IMAGES.services on regen — that namespace is populated by the
 * MCP image server (scripts/mcp-image-server.mjs) and has no entries in
 * IMAGE_QUERIES, so blowing it away would wipe every curated service pick.
 */
function readExistingServices(): Record<string, string> {
  if (!existsSync(OUT)) return {}
  const src = readFileSync(OUT, 'utf8')
  const block = src.match(/services:\s*\{([\s\S]*?)\n\s*\}/)
  if (!block) return {}
  const out: Record<string, string> = {}
  for (const m of block[1].matchAll(/['"]([^'"]+)['"]\s*:\s*['"]([^'"]+)['"]/g)) {
    out[m[1]] = m[2]
  }
  return out
}

async function main() {
  console.log('\n  Fetching Pexels photos...\n')

  const hero = await pickPhoto(IMAGE_QUERIES.hero)
  const fenceTypes = await pickRecord(IMAGE_QUERIES.fenceTypes as Record<string, string>)
  const neighborhoods = await pickRecord(IMAGE_QUERIES.neighborhoods as Record<string, string>)
  const resources = await pickRecord(IMAGE_QUERIES.resources as Record<string, string>)
  const gallery = await pickMany(IMAGE_QUERIES.gallery)
  const services = readExistingServices()
  if (Object.keys(services).length) {
    console.log(`  ✓ preserved ${Object.keys(services).length} curated IMAGES.services entries`)
  }

  const banner = `/**\n * Auto-generated by \`npm run fetch-images\`. Do not edit by hand,\n * except for the IMAGES.services block (managed by the MCP image server).\n */\n`
  const body = `export const IMAGES = ${JSON.stringify(
    { hero, fenceTypes, neighborhoods, resources, gallery, services },
    null,
    2,
  )}\n`
    // Re-annotate the services namespace so TS allows arbitrary slug keys.
    .replace(/("services":\s*\{[^}]*\})/, '$1 as Record<string, string>')

  mkdirSync(dirname(OUT), { recursive: true })
  writeFileSync(OUT, banner + body, 'utf8')
  console.log(`\n  Wrote ${OUT}\n`)
}

main().catch((err) => {
  console.error('\n  Fetch failed:', err.message, '\n')
  process.exit(1)
})
