/**
 * Auto-generated by `npm run fetch-images`. Do not edit by hand.
 *
 * Seed values below use Unsplash placeholders so the site builds before
 * Pexels has been run. Run the fetcher (with PEXELS_API_KEY in .env) to
 * replace them with topically-matched Pexels photos.
 */
export const IMAGES = {
  hero: 'https://unsplash.com/photos/JLdl9Bq8eGU/download?w=1600&q=80',
  fenceTypes: {
    'wood-privacy': 'https://images.unsplash.com/photo-1597215593569-2b67d4ad6ca5?auto=format&fit=crop&w=1200&q=80',
    'vinyl': 'https://images.unsplash.com/photo-1531386450460-39de17ce486f?auto=format&fit=crop&w=1200&q=80',
    'aluminum': 'https://images.unsplash.com/photo-1505852679233-d9fd70aff56d?auto=format&fit=crop&w=1200&q=80',
    'chain-link': 'https://images.unsplash.com/photo-1494522358652-f30e61a60313?auto=format&fit=crop&w=1200&q=80',
    'horizontal-privacy': 'https://images.unsplash.com/photo-1582036930868-d4e4eaf4f9f5?auto=format&fit=crop&w=1200&q=80',
    'farm-ranch': 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
  },
  neighborhoods: {
    'belle-meade': 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80',
    'green-hills': 'https://images.unsplash.com/photo-1592595896616-c37162298647?auto=format&fit=crop&w=1200&q=80',
    'east-nashville': 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1200&q=80',
    'germantown': 'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=1200&q=80',
    'brentwood': 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80',
    'franklin': 'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&w=1200&q=80',
    'twelve-south': 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80',
    'sylvan-park': 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=1200&q=80',
    'hendersonville': 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80',
    'mount-juliet': 'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=1200&q=80',
    'hermitage': 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80',
    'forest-hills': 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1200&q=80',
  },
  resources: {
    'wood-vs-vinyl-nashville': 'https://images.unsplash.com/photo-1597215593569-2b67d4ad6ca5?auto=format&fit=crop&w=1200&q=80',
    'best-fences-for-dogs': 'https://images.unsplash.com/photo-1494522358652-f30e61a60313?auto=format&fit=crop&w=1200&q=80',
    'pool-fence-safety-tn': 'https://images.unsplash.com/photo-1505852679233-d9fd70aff56d?auto=format&fit=crop&w=1200&q=80',
    'metro-nashville-permits': 'https://images.unsplash.com/photo-1531386450460-39de17ce486f?auto=format&fit=crop&w=1200&q=80',
    'fence-cost-breakdown': 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
    'horizontal-cedar-trend': 'https://images.unsplash.com/photo-1582036930868-d4e4eaf4f9f5?auto=format&fit=crop&w=1200&q=80',
  },
  gallery: [
    'https://images.unsplash.com/photo-1597215593569-2b67d4ad6ca5?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1505852679233-d9fd70aff56d?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1531386450460-39de17ce486f?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1582036930868-d4e4eaf4f9f5?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1597100190876-3a47e4d61df3?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1494522358652-f30e61a60313?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1597215593569-2b67d4ad6ca5?auto=format&fit=crop&w=900&q=80',
  ],
} as const
